version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    ports:
      - '13306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
volumes:
  mysql_data:
