name: Build
on: 
  push:
  workflow_dispatch:
  pull_request_target:
jobs:
  Build-and-Test-CDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          npm ci
          npm run build
          npm run test
        working-directory: ./cdk
  Build-and-Test-Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          npm ci
          npm run build
        working-directory: ./webapp
